services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: infra-${PROJECT_SLUG}-zookeeper
    ports:
      - "${HOST_PORT_ZOOKEEPER}:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - ${PROJECT_DATA_PATH}/zookeeper/data:/var/lib/zookeeper/data
      - ${PROJECT_DATA_PATH}/zookeeper/log:/var/lib/zookeeper/log
    networks:
      - df-network
    labels:
      managed-by: docker-framework
      df.type: infra
      df.resource: zookeeper
      df.project: ${PROJECT_SLUG}
    healthcheck:
      test: echo ruok | nc localhost 2181 | grep imok
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

networks:
  df-network:
    name: df-network
    external: true
